version: "3.8"
volumes:
  portainer_data:
    name: portainer_data

services:
  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - 19000:9000
      - 18000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
