version: "3.8"
services:
  static-http:
    build: ../apache-php-image/
    container_name: static-http

  dynamic-http:
    build: ../express-image/
    container_name: dynamic-http

  reverse-proxy:
    build: .
    container_name: reverse-proxy
    ports:
      - 8080:80
